/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadorateste;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

import calculadorateste.calculadora;

public class testecalculadora{

    private calculadora obcal;

    @Before
    public void setUp()throws Exception {
        obcal = new calculadora();
    }
    
    @Test
    public void testarSomaPositivo() {
        assertEquals("", 6, obcal.soma(3, 3));
    }
    @Test
    public void testarSomaNegativos() {
        assertEquals("", -4, obcal.soma(-9, 5));
    }

    @Test
    public void testarsubtracaoPositivo() {
        assertEquals("", 3, obcal.subtracao(6, 3));
    }

    @Test
    public void testarsubtracaoNegativo() {
        assertEquals("", -8, obcal.subtracao(2, 10));
    }

    @Test
    public void testarmultiplicacaoPositivo() {
        assertEquals("", 25, obcal.multiplicacao(5, 5));
    }

    @Test
    public void testarmultiplicacaoNegativo() {
        assertEquals("", 18, obcal.multiplicacao(-3, -6));
    }

    @Test
    public void testardivisaopositivo() {
        assertEquals("", 9, obcal.divisao(18, 2));
    }

    @Test
    public void testardivisaoNegativo() {
        assertEquals("", -24, obcal.divisao(-48, 2));
    }
    
    @Test(expected = ArithmeticException.class)
    public void testDivisaoPorZero() {
        obcal.divisao(10, 0);
        System.out.println("A operação de divisão por zero não deveria chegar aqui");
    }
}